notifications:
  email: false
matrix:
  include:
  - sudo: required
    services:
      - docker
    arch: amd64
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
      - docker
    arch: amd64
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
      - PRE_CMD=linux32
  - sudo: required
    services:
      - docker
    arch: ppc64le
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux2014_ppc64le
  - sudo: required
    services:
      - docker
    arch: aarch64
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
  - sudo: required
    services:
      - docker
    arch: s390x
    env:
      - DOCKER_IMAGE=quay.io/pypa/manylinux2014_s390x
install:
  - docker pull $DOCKER_IMAGE
script:
  - pwd
  - ls -la
  - if [[ "${TRAVIS_TAG}" == "" ]]; then unset TWINE_USERNAME; fi
  - docker run --rm -v `pwd`:/io -e TWINE_USERNAME -e TWINE_PASSWORD $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
