blank_issues_enabled: true
contact_links:
  - name: ‚ùì Question
    url: https://github.com/inducer/pyopencl/discussions/categories/q-a
    about: Ask and answer questions about PyOpenCL on Discussions
  - name: üîß Troubleshooting
    url: https://github.com/inducer/pyopencl/discussions/categories/troubleshooting
    about: For troubleshooting help, see the Discussions
